AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda function with cfn-response.
Parameters:
    LambdaName:
        Type: String
        Default: Example-NodeJS
    DefineRoleName:
        Type: String
        Default: IAMRoleForLambda-lambda-role-arn

Resources:
    Lambda:
        Type: AWS::Lambda::Function
        Properties:
            Runtime: python3.8
            Role: arn:aws:iam::777970765756:role/BasicLambdaIAMRole
            FunctionName: !Ref LambdaName
            Handler: index.handler
            Code:
                ZipFile: |
                    import json
                    import urllib3
                    import os

                    def lambda_handler(event, context):
                        # TODO implement
                        http = urllib3.PoolManager()
                        data = {"text": "Sample message from DinoCloudBot Lambda Function"}
                        r = http.request("POST",
                            os.environ['slack_url'],
                            body = json.dumps(data),
                            headers = {"Content-Type": "application/json"})
                        return {
                            'statusCode': 200,
                            'body': json.dumps('Hello from Lambda!')
                        }
            Description: Invoke a function during stack creation.
            TracingConfig:
                Mode: Active